from flask import Flask, render_template, request, jsonify
import random

app = Flask(__name__)

# Extended Thoughts and Quotes in English (Sample of 150, expandable to 500)
thoughts_quotes_en = [
    "The best way to predict the future is to create it. - Peter Drucker",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "What we think, we become. - Buddha",
    "The mind is everything. What you think you become. - Buddha",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
    "Peace comes from within. Do not seek it without. - Buddha",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. - Lao Tzu",
    "The true measure of a person is how they treat someone who can do nothing for them. - Unknown",
    "Change is the law of life. - John F. Kennedy",
    "To handle yourself, use your head; to handle others, use your heart. - Eleanor Roosevelt",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "A journey is best measured in friends, rather than miles. - Tim Cahill",
    "The best preparation for tomorrow is doing your best today. - H. Jackson Brown Jr.",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "The secret of getting ahead is getting started. - Mark Twain",
    "I have not failed. I’ve just found 10,000 ways that won’t work. - Thomas Edison",
    "The best dreams happen when you’re awake. - Cherie Gilderbloom",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Act as if what you do makes a difference. It does. - William James",
    "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome. - Booker T. Washington",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Happiness is not in the mere possession of money; it lies in the joy of achievement. - Franklin D. Roosevelt",
    "The greatest wealth is to live content with little. - Plato",
    "A man who stands for nothing will fall for anything. - Malcolm X",
    "The best way out is always through. - Robert Frost",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "The best time to plant a tree was twenty years ago. The second best time is now. - Chinese Proverb",
    "You cannot shake hands with a clenched fist. - Indira Gandhi",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "Kindness is a language which the deaf can hear and the blind can see. - Mark Twain",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "The greatest pleasure in life is doing what people say you cannot do. - Walter Bagehot",
    "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
    "We do not see things as they are, we see them as we are. - Anaïs Nin",
    "The only way to make sense out of change is to plunge into it, move with it, and join the dance. - Alan Watts",
    "Life shrinks or expands in proportion to one’s courage. - Anaïs Nin",
    "The unexamined life is not worth living. - Socrates",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "The greatest mistake you can make in life is to be continually fearing you will make one. - Elbert Hubbard",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle",
    "A smooth sea never made a skilled sailor. - Franklin D. Roosevelt",
    "The harder the conflict, the more glorious the triumph. - Thomas Paine",
    "Dream big and dare to fail. - Norman Vaughan",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injury. - Marcus Aurelius",
    "It is not the length of life, but the depth of life that matters. - Ralph Waldo Emerson",
    "The only impossible journey is the one you never begin. - Tony Robbins",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "The more you know, the more you realize you don’t know. - Aristotle",
    "A friend is one who knows you and loves you just the same. - Elbert Hubbard",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
    "In the end, we only regret the chances we didn’t take. - Lewis Carroll",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "The only way to discover the limits of the possible is to go beyond them into the impossible. - Arthur C. Clarke",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "The greatest gift of life is friendship, and I have received it. - Hubert H. Humphrey",
    "We don’t stop playing because we grow old; we grow old because we stop playing. - George Bernard Shaw",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "The man who moves a mountain begins by carrying away small stones. - Confucius",
    "It is never too late to be what you might have been. - George Eliot",
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "Simplicity is the ultimate sophistication. - Leonardo da Vinci",
    "A goal without a plan is just a wish. - Antoine de Saint-Exupéry",
    "Life is not about finding yourself. Life is about creating yourself. - George Bernard Shaw",
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The art of living is more like wrestling than dancing. - Marcus Aurelius",
    "The only real mistake is the one from which we learn nothing. - Henry Ford",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "If you can dream it, you can do it. - Walt Disney",
    "The best way to cheer yourself up is to try to cheer somebody else up. - Mark Twain",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us. - Helen Keller",
    "The mind is like a parachute; it works best when it’s open. - Thomas Dewar",
    "The greatest discovery of all time is that a person can change his future by merely changing his attitude. - Oprah Winfrey",
    "What we achieve inwardly will change outer reality. - Plutarch",
    "Don’t let yesterday take up too much of today. - Will Rogers",
    "The most wasted of days is one without laughter. - E.E. Cummings",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it. - Jordan Belfort",
    "You cannot swim for new horizons until you have courage to lose sight of the shore. - William Faulkner",
    "Life is a succession of lessons which must be lived to be understood. - Ralph Waldo Emerson",
    "The difference between ordinary and extraordinary is that little extra. - Jimmy Johnson",
    "Success is not the absence of obstacles, but the courage to push through. - Unknown",
    "The best way to appreciate your job is to imagine yourself without one. - Oscar Wilde",
    "The greatest risk is not taking any risk. - Mark Zuckerberg",
    "The key to immortality is first living a life worth remembering. - Bruce Lee",
    "You can’t cross the sea merely by standing and staring at the water. - Rabindranath Tagore",
    "The best and most beautiful things in the world cannot be seen or even touched—they must be felt with the heart. - Helen Keller",
    "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing. - George Bernard Shaw",
    "The only source of knowledge is experience. - Albert Einstein",
    "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge. - Stephen Hawking",
    "If you want to go fast, go alone. If you want to go far, go together. - African Proverb",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. - Ralph Waldo Emerson",
    "A ship in harbor is safe, but that is not what ships are built for. - John A. Shedd",
    "The best way to find out if you can trust somebody is to trust them. - Ernest Hemingway",
    "The only thing that makes life possible is permanent, intolerable uncertainty: not knowing what comes next. - Ursula K. Le Guin",
    "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
    "Life isn’t about waiting for the storm to pass; it’s about learning to dance in the rain. - Vivian Greene",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Confucius",
    "Do not judge me by my successes, judge me by how many times I fell down and got back up again. - Nelson Mandela",
    "The best way to make your dreams come true is to wake up. - Paul Valéry",
    "You can never plan the future by the past. - Edmund Burke",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "The best way to get things done is to simply begin. - Unknown",
    "The greatest happiness you can have is knowing that you do not necessarily require happiness. - William Saroyan",
    "Success does not consist in never making mistakes but in never making the same one a second time. - George Bernard Shaw",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "You don’t learn to walk by following rules. You learn by doing, and by falling over. - Richard Branson",
    "The best way to predict your future is to create it. - Abraham Lincoln",
    "The only thing standing between you and your dreams is the will to try and the belief that it is actually possible. - Joel Brown",
    # ... (Continue adding up to ~100, or expand to 500 with more quotes from diverse sources)
    "The world is full of obvious things which nobody by any chance ever observes. - Sherlock Holmes"
    # Add 400 more quotes from philosophers, authors, and cultural figures to reach 500
]

# Extended Thoughts and Quotes in Arabic (Sample of 150, expandable to 500)
thoughts_quotes_ar = [
    "أفضل طريقة لتوقع المستقبل هي خلقه. - بيتر دراكر",
    "الحياة هي ما يحدث وأنت مشغول بصنع خطط أخرى. - جون لينون",
    "الطريقة الوحيدة لعمل عمل عظيم هي حب ما تفعله. - ستيف جوبز",
    "في وسط الصعوبة تكمن الفرصة. - ألبرت أينشتاين",
    "السعادة ليست شيئًا جاهزًا، إنما تأتي من أفعالك الخاصة. - الدالاي لاما",
    "أعظم مجد في الحياة ليس في عدم السقوط، بل في النهوض كل مرة نسقط فيها. - نيلسون مانديلا",
    "إذا آمنت بقدرتك، فأنت في منتصف الطريق. - ثيودور روزفلت",
    "الحد الوحيد لتحقيق غدنا هو شكوكنا اليوم. - فرانكلين د. روزفلت",
    "النجاح ليس نهائيًا، والفشل ليس قاتلاً: الشجاعة للاستمرار هي ما يهم. - ونستون تشرشل",
    "نصبح ما نفكر فيه. - بوذا",
    "العقل هو كل شيء. نصبح ما نفكر فيه. - بوذا",
    "لا تعش في الماضي، ولا تحلم بالمستقبل، ركز عقلك على اللحظة الحالية. - بوذا",
    "السلام يأتي من داخلك. لا تبحث عنه خارجًا. - بوذا",
    "رحلة ألف ميل تبدأ بخطوة واحدة. - لاوتسي",
    "أن تحببك شخص بعمق يعطيك القوة، بينما حبك لشخص بعمق يعطيك الشجاعة. - لاوتسي",
    "قياس الإنسان الحقيقي يكمن في كيفية تعامله مع من لا يستطيع مساعدته. - غير معروف",
    "التغيير هو قانون الحياة. - جون إف. كينيدي",
    "للتحكم بنفسك، استخدم عقلك؛ للتحكم بالآخرين، استخدم قلبك. - إليانور روزفلت",
    "الشيء الوحيد الذي يجب أن نخافه هو الخوف نفسه. - فرانكلين د. روزفلت",
    "لا يهم كم تبطئ الخطوات طالما أنك لا تتوقف. - كونفوشيوس",
    "الرحلة تقاس أفضل بأصدقاء وليس بأميال. - تيم كاهيل",
    "أفضل استعداد للغد هو بذل قصارى جهدك اليوم. - إتش. جاكسون براون جونيور",
    "تفوّت على 100% من الفرص التي لا تُحاول أخذها. - واين غريتزكي",
    "طريقة البدء هي التوقف عن الحديث والبدء بالعمل. - والت ديزني",
    "لا تنظر إلى الساعة؛ افعل ما تفعله. استمر. - سام ليفنسون",
    "سر التقدم يكمن في البدء. - مارك توين",
    "لم أفشل، لقد وجدت 10,000 طريقة لا تعمل. - توماس إديسون",
    "أفضل الأحلام تحدث وأنت مستيقظ. - شيري غيلدربلوم",
    "ما تحصل عليه بتحقيق أهدافك ليس مهمًا مثل ما تصبح عليه بتحقيقها. - زيغ زيغلار",
    "الشخص الوحيد الذي يُقدّر لك أن تصبح هو الذي تقرر أن تكونه. - رالف والدو إيمرسون",
    "تصرف كما لو أن ما تفعله يحدث فرقًا. ويحدث بالفعل. - وليام جيمس",
    "النجاح يُقاس ليس بمركز الشخص في الحياة بقدر ما يُقاس بالعقبات التي تغلبها. - بوكر ت. واشنطن",
    "المستقبل لمن يؤمن بجمال أحلامه. - إليانور روزفلت",
    "لن تكون أبدًا كبيرًا جدًا لوحددت هدفًا جديدًا أو حلمت بحلم جديد. - سي. إس. لويس",
    "السعادة ليست في امتلاك المال فحسب؛ بل في فرحة الإنجاز. - فرانكلين د. روزفلت",
    "أعظم ثروة هي العيش راضيًا بقليل. - أفلاطون",
    "الرجل الذي لا يقف لشيء سيخضع لكل شيء. - مالكوم إكس",
    "أفضل طريقة للخروج هي الدخول دائمًا. - روبرت فروست",
    "أن تكون نفسك في عالم يحاول باستمرار جعلك شيئًا آخر هو الإنجاز الأعظم. - رالف والدو إيمرسون",
    "في أحلك لحظاتنا يجب أن نركز لنرى النور. - أرسطو",
    "غرض حياتنا هو أن نكون سعداء. - الدالاي لاما",
    "إذا أردت رفع نفسك، ارفع شخصًا آخر. - بوكر ت. واشنطن",
    "أفضل وقت لزراعة شجرة كان قبل عشرين عامًا. الوقت الثاني الأفضل هو الآن. - مثل صيني",
    "لا يمكنك مصافحة يد مغلقة. - إنديرا غاندي",
    "الحكمة الحقيقية الوحيدة هي أن تعرف أنك لا تعرف شيئًا. - سقراط",
    "اللطف لغة يمكن للأصم سماعها والعمي رؤيتها. - مارك توين",
    "الحياة إما مغامرة جريئة أو لا شيء على الإطلاق. - هيلين كيلر",
    "أعظم متعة في الحياة هي فعل ما يقول الناس إنك لا تستطيع. - والتر باجيهوت",
    "من لديه لماذا يعيش يمكنه تحمل أي كيف. - فريدريش نيتشه",
    "نحن لا نرى الأشياء كما هي، بل كما نحن. - أنايس نين",
    "الطريقة الوحيدة لفهم التغيير هي الانغماس فيه، التحرك معه، والانضمام إلى الرقصة. - آلان واتس",
    "الحياة تتقلص أو تتسع بنسبة شجاعتك. - أنايس نين",
    "الحياة غير المفحوصة لا تستحق العيش. - سقراط",
    "كن التغيير الذي تريد رؤيته في العالم. - مهاتما غاندي",
    "افعل ما تستطيع، بما لديك، حيث أنت. - ثيودور روزفلت",
    "اجعل وجهك دائمًا نحو الشمس، فستسقط الظلال خلفك. - والت ويتمان",
    "أكبر خطأ في الحياة هو أن تخاف باستمرار من ارتكاب خطأ. - إلبيرت هوبارد",
    "نحن ما نفعله مرارًا وتكرارًا. التميز، إذًا، ليس فعلاً، بل عادة. - أرسطو",
    "البحر الهادئ لا يصنع بحارًا ماهرًا. - فرانكلين د. روزفلت",
    "كلما كان الصراع أصعب، كان الانتصار أكثر عظمة. - توماس بين",
    "احلم بأحلام كبيرة وتجرأ على الفشل. - نورمان فوغان",
    "ما خلفنا وما أمامنا أمور صغيرة مقارنة بما بداخلنا. - رالف والدو إيمرسون",
    "أفضل انتقام هو أن تكون مختلفًا عمن أساء إليك. - ماركوس أوريليوس",
    "ليس طول الحياة هو ما يهم، بل عمقها. - رالف والدو إيمرسون",
    "الرحلة المستحيلة الوحيدة هي التي لا تبدأها أبدًا. - توني روبنز",
    "النجاح هو مجموع الجهود الصغيرة المتكررة يومًا بعد يوم. - روبرت كولير",
    "كلما عرفت أكثر، أدركت أنك لا تعرف. - أرسطو",
    "الصديق هو من يعرفك ويحبك كما أنت. - إلبيرت هوبارد",
    "الحياة بسيطة جدًا، لكننا نصر على تعقيدها. - كونفوشيوس",
    "أكبر مغامرة يمكنك خوضها هي أن تعيش حياة أحلامك. - أوبرا وينفري",
    "في النهاية، نأسف فقط على الفرص التي لم نأخذها. - لويس كارول",
    "لا تسلك الطريق الذي يقودك، بل اذهب حيث لا يوجد طريق واترك أثرًا. - رالف والدو إيمرسون",
    "الطريقة الوحيدة لمعرفة حدود الممكن هي التجاوز إلى المستحيل. - آرثر سي. كلارك",
    "وقتك محدود، فلا تضيعه في عيش حياة شخص آخر. - ستيف جوبز",
    "أعظم هدايا الحياة هي الصداقة، وقد حصلت عليها. - هوبيرت إتش. همفري",
    "لا نتوقف عن اللعب لأننا نكبر؛ بل نكبر لأننا نتوقف عن اللعب. - جورج برنارد شو",
    "حوّل جروحك إلى حكمة. - أوبرا وينفري",
    "الرجل الذي ينقل جبلًا يبدأ بحمل الحجارة الصغيرة. - كونفوشيوس",
    "لم يفت الأوان أبدًا لتكون ما كنت تود أن تكونه. - جورج إليوت",
    "الشيء الوحيد اللازم لانتصار الشر هو أن يقف الأخيار مكتوفي الأيدي. - إدموند بيرك",
    "البساطة هي أعلى درجات الرقي. - ليوناردو دا فينشي",
    "الهدف بدون خطة هو مجرد أمنية. - أنطوان دي سانت إكزوبيري",
    "الحياة ليست عن إيجاد نفسك، بل عن خلق نفسك. - جورج برنارد شو",
    "أفضل طريقة لتجد نفسك هي أن تفقد نفسك في خدمة الآخرين. - مهاتما غاندي",
    "لا يجب أن تكون عظيمًا لتبدأ، لكن يجب أن تبدأ لتكون عظيمًا. - زيغ زيغلار",
    "فن العيش يشبه المصارعة أكثر من الرقص. - ماركوس أوريليوس",
    "الخطأ الحقيقي الوحيد هو الذي لا نتعلم منه شيئًا. - هنري فورد",
    "العيش هو أندر شيء في العالم، معظم الناس فقط موجودون، هذا كل شيء. - أوسكار وايلد",
    "الشخص الذي لم يخطئ أبدًا لم يجرب شيئًا جديدًا. - ألبرت أينشتاين",
    "إذا استطعت أن تحلم به، يمكنك أن تفعله. - والت ديزني",
    "أفضل طريقة لتشجيع نفسك هي محاولة تشجيع شخص آخر. - مارك توين",
    "عندما يغلق باب السعادة، يفتح آخر؛ لكن غالبًا ننظر طويلاً إلى الباب المغلق فلا نرى الذي فتح لنا. - هيلين كيلر",
    "العقل مثل المظلة؛ يعمل بشكل أفضل عندما يكون مفتوحًا. - توماس ديوار",
    "أعظم اكتشاف في كل العصور هو أن الإنسان يستطيع تغيير مستقبله بمجرد تغيير موقفه. - أوبرا وينفري",
    "ما نحققه داخليًا سيغير الواقع الخارجي. - بلوتارخ",
    "لا تدع الأمس يأخذ الكثير من اليوم. - ويل روجرز",
    "اليوم الأكثر إهدارًا هو يوم بلا ضحك. - إي. إي. كامينغز",
    "الشيء الوحيد الذي يقف بينك وبين هدفك هو القصة التي تستمر في إخبار نفسك عن سبب عدم قدرتك على تحقيقه. - جوردان بيلفورت",
    "لا يمكنك السباحة إلى آفاق جديدة حتى تتجرأ على فقدان رؤية الشاطئ. - وليام فوكنر",
    "الحياة سلسلة من الدروس التي يجب أن نعيشها لنفهمها. - رالف والدو إيمرسون",
    "الفرق بين العادي والاستثنائي هو ذلك القليل الإضافي. - جيمي جونسون",
    "النجاح ليس غياب العقبات، بل الشجاعة للمضي قدمًا. - غير معروف",
    "أفضل طريقة لتقدير وظيفتك هي أن تتخيل نفسك بدون واحدة. - أوسكار وايلد",
    "أكبر مخاطرة هي عدم أخذ أي مخاطرة. - مارك زوكربيرغ",
    "مفتاح الخلود هو أن تعيش حياة تستحق التذكر. - بروس لي",
    "لا يمكنك عبور البحر بالوقوف والتحديق في الماء فقط. - رابندرانات طاغور",
    "أفضل وأجمل الأشياء في العالم لا يمكن رؤيتها أو لمسها—يجب أن تُشعر بها بالقلب. - هيلين كيلر",
    "الحياة التي تُقضى في ارتكاب الأخطاء ليست فقط أكثر شرفًا، بل أكثر فائدة من حياة تُقضى في لا شيء. - جورج برنارد شو",
    "مصدر المعرفة الوحيد هو التجربة. - ألبرت أينشتاين",
    "أعظم أعداء المعرفة ليس الجهل، بل وهم المعرفة. - ستيفن هوكينغ",
    "إذا أردت أن تذهب بسرعة، اذهب بمفردك. إذا أردت أن تذهب بعيدًا، اذهب معًا. - مثل أفريقي",
    "الطريقة الوحيدة لتحقيق المستحيل هي أن تؤمن أنه ممكن. - تشارلز كينغسلي",
    "غرض الحياة ليس أن تكون سعيدًا. بل أن تكون مفيدًا، مشرفًا، رحيمًا، وأن تترك أثرًا بأنك عشت وعشت جيدًا. - رالف والدو إيمرسون",
    "السفينة في الميناء آمنة، لكن هذا ليس ما بُنيت السفن من أجله. - جون إيه. شيد",
    "أفضل طريقة لمعرفة ما إذا كنت تستطيع الوثوق بشخص ما هي أن تثق به. - إرنست همنغواي",
    "الشيء الوحيد الذي يجعل الحياة ممكنة هو عدم اليقين الدائم وغير المحتمل: عدم معرفة ما سيأتي بعد ذلك. - أورسولا ك. لو غوين",
    "لديك داخلك الآن كل ما تحتاجه للتعامل مع أي شيء يمكن أن يلقيه العالم عليك. - براين تريسي",
    "الحياة ليست انتظار انتهاء العاصفة؛ بل تعلم كيف ترقص تحت المطر. - فيفيان غرين",
    "أعظم مجد في الحياة ليس في عدم السقوط أبدًا، بل في النهوض كل مرة نسقط فيها. - كونفوشيوس",
    "لا تحكم عليّ بنجاحاتي، بل بحساب كم مرة سقطت ونهضت مجددًا. - نيلسون مانديلا",
    "أفضل طريقة لتحقيق أحلامك هي أن تستيقظ. - بول فاليري",
    "لا يمكنك التخطيط للمستقبل بالماضي. - إدموند بيرك",
    "الحد الوحيد لتحقيق غدنا سيكون شكوكنا اليوم. - فرانكلين د. روزفلت",
    "الحياة 10% مما يحدث لنا و90% كيف نرد عليه. - تشارلز آر. سويندول",
    "أفضل طريقة لإنجاز الأمور هي أن تبدأ ببساطة. - غير معروف",
    "أعظم سعادة يمكن أن تحصل عليها هي معرفة أنك لا تحتاج بالضرورة إلى السعادة. - وليام سارويان",
    "النجاح لا يكمن في عدم ارتكاب الأخطاء، بل في عدم تكرار نفس الخطأ مرة أخرى. - جورج برنارد شو",
    "الطريقة الوحيدة لعمل عمل عظيم هي حب ما تفعله. - ستيف جوبز",
    "لا تتعلم المشي باتباع القواعد، بل تتعلم بالفعل وبالسقوط. - ريتشارد برانسون",
    "أفضل طريقة لتوقع مستقبلك هي خلقه. - أبراهام لينكولن",
    "الشيء الوحيد الذي يقف بينك وبين أحلامك هو الإرادة للمحاولة والإيمان بأن ذلك ممكن بالفعل. - جويل براون",
    # ... (Continue adding up to ~100, or expand to 500 with more Arabic proverbs and quotes)
    "الصبر يغير الحياة. - مثل عربي"
    # Add 400 more Arabic quotes and proverbs to reach 500
]

# Extended Trivia Questions (Sample of ~100 English and Arabic, expandable to 500 each)
trivia_questions = [
    # English Trivia Questions
    {"question": "What is the capital of Brazil?", "options": ["Canberra", "Berlin", "São Paulo", "Rio de Janeiro"], "answer": "Rio de Janeiro"},
    {"question": "Who painted the Mona Lisa?", "options": ["Van Gogh", "Barnebas", "Da Vinci", "Picasso"], "answer": "Da Vinci"},
    {"question": "What is the largest planet in the solar system?", "options": ["Earth", "Jupiter", "Saturn", "Neptune"], "answer": "Jupiter"},
    {"question": "What is the capital of Japan?", "options": ["Seoul", "Beijing", "Tokyo", "Bangkok"], "answer": "Tokyo"},
    {"question": "Which country is known as the Land of the Rising Sun?", "options": ["China", "Japan", "Thailand", "Vietnam"], "answer": "Japan"},
    {"question": "What is the tallest mountain in the world?", "options": ["K2", "Kangchenjunga", "Everest", "Makalu"], "answer": "Everest"},
    {"question": "Which planet is known for its rings?", "options": ["Mars", "Jupiter", "Saturn", "Uranus"], "answer": "Saturn"},
    {"question": "What is the capital of France?", "options": ["Madrid", "Paris", "Rome", "Berlin"], "answer": "Paris"},
    {"question": "Who was the first President of the United States?", "options": ["Jefferson", "Washington", "Adams", "Lincoln"], "answer": "Washington"},
    {"question": "What is the largest desert in the world?", "options": ["Sahara", "Gobi", "Antarctic", "Arabian"], "answer": "Antarctic"},
{"question": "What is the capital of Brazil?", "options": ["Canberra", "Berlin", "São Paulo", "Rio de Janeiro"], "answer": "Rio de Janeiro"},
    {"question": "Who painted the Mona Lisa?", "options": ["Van Gogh", "Bannebas", "Da Vinci", "Picasso"], "answer": "Da Vinci"},
    {"question": "What is the largest planet in the solar system?", "options": ["Earth", "Jupiter", "Saturn", "Neptune"], "answer": "Jupiter"},
    {"question": "Which country is known as the Land of the Rising Sun?", "options": ["China", "Thailand", "Japan", "Vietnam"], "answer": "Japan"},
    {"question": "What is the tallest mountain in the world?", "options": ["K2", "Kangchenjunga", "Everest", "Makalu"], "answer": "Everest"},
    {"question": "Which planet is known for its rings?", "options": ["Mars", "Jupiter", "Saturn", "Uranus"], "answer": "Saturn"},
    {"question": "What is the capital of France?", "options": ["Madrid", "Paris", "Rome", "Berlin"], "answer": "Paris"},
    {"question": "Who was the first President of the United States?", "options": ["Thomas Jefferson", "Washington", "Adams", "Lincoln"], "answer": "Washington"},
    {"question": "What is the largest desert in the world?", "options": ["Sahara", "Gobi", "Antarctic", "Arabian"], "answer": "Antarctic"},
    {"question": "Which element has the chemical symbol O?", "options": ["Gold", "Oxygen", "Iron", "Silver"], "answer": "Oxygen"},
    {"question": "What is the capital of Australia?", "options": ["Sydney", "Melbourne", "Canberra", "Perth"], "answer": "Canberra"},
    {"question": "Who wrote 'Romeo and Juliet'?", "options": ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], "answer": "William Shakespeare"},
    {"question": "What is the smallest country in the world by land area?", "options": ["Monaco", "Nauru", "Vatican City", "San Marino"], "answer": "Vatican City"},
    {"question": "Which animal is known as the 'King of the Jungle'?", "options": ["Elephant", "Lion", "Tiger", "Bear"], "answer": "Lion"},
    {"question": "What is the main ingredient in guacamole?", "options": ["Tomato", "Avocado", "Onion", "Pepper"], "answer": "Avocado"},
    {"question": "Which planet is closest to the Sun?", "options": ["Venus", "Mercury", "Earth", "Mars"], "answer": "Mercury"},
    {"question": "What is the capital of Canada?", "options": ["Toronto", "Vancouver", "Ottawa", "Montreal"], "answer": "Ottawa"},
    {"question": "Who discovered penicillin?", "options": ["Marie Curie", "Alexander Fleming", "Louis Pasteur", "Isaac Newton"], "answer": "Alexander Fleming"},
    {"question": "What is the longest river in the world?", "options": ["Amazon", "Nile", "Yangtze", "Mississippi"], "answer": "Nile"},
    {"question": "Which sport is played at Wimbledon?", "options": ["Cricket", "Tennis", "Soccer", "Golf"], "answer": "Tennis"},
    {"question": "What is the capital of Egypt?", "options": ["Alexandria", "Cairo", "Luxor", "Giza"], "answer": "Cairo"},
    {"question": "Who was the first man to step on the moon?", "options": ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"], "answer": "Neil Armstrong"},
    {"question": "What is the largest ocean on Earth?", "options": ["Atlantic", "Indian", "Arctic", "Pacific"], "answer": "Pacific"},
    {"question": "Which gas makes up most of Earth’s atmosphere?", "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], "answer": "Nitrogen"},
    {"question": "What is the capital of India?", "options": ["Mumbai", "Delhi", "Bangalore", "Kolkata"], "answer": "Delhi"},
    {"question": "Who painted the Sistine Chapel ceiling?", "options": ["Leonardo da Vinci", "Michelangelo", "Raphael", "Titian"], "answer": "Michelangelo"},
    {"question": "What is the hardest natural substance known?", "options": ["Gold", "Diamond", "Iron", "Quartz"], "answer": "Diamond"},
    {"question": "Which country hosted the 2016 Summer Olympics?", "options": ["China", "Brazil", "Russia", "United States"], "answer": "Brazil"},
    {"question": "What is the capital of South Africa?", "options": ["Johannesburg", "Cape Town", "Pretoria", "Durban"], "answer": "Pretoria"},
    {"question": "Which instrument has 88 keys?", "options": ["Guitar", "Piano", "Violin", "Drums"], "answer": "Piano"},
    {"question": "What is the capital of Russia?", "options": ["St. Petersburg", "Moscow", "Novosibirsk", "Kazan"], "answer": "Moscow"},
    {"question": "Who developed the theory of relativity?", "options": ["Isaac Newton", "Albert Einstein", "Stephen Hawking", "Niels Bohr"], "answer": "Albert Einstein"},
    {"question": "What is the largest bird in the world?", "options": ["Eagle", "Ostrich", "Penguin", "Albatross"], "answer": "Ostrich"},
    {"question": "What is the capital of Italy?", "options": ["Venice", "Milan", "Rome", "Florence"], "answer": "Rome"},
    {"question": "Which gas is most abundant in the universe?", "options": ["Oxygen", "Helium", "Hydrogen", "Carbon"], "answer": "Hydrogen"},
    {"question": "Who was the first woman to win a Nobel Prize?", "options": ["Marie Curie", "Jane Addams", "Pearl Buck", "Mother Teresa"], "answer": "Marie Curie"},
    {"question": "What is the capital of Spain?", "options": ["Barcelona", "Madrid", "Seville", "Valencia"], "answer": "Madrid"},
    {"question": "Which fruit is known for its spiky exterior?", "options": ["Pineapple", "Mango", "Banana", "Apple"], "answer": "Pineapple"},
    {"question": "What is the capital of Japan?", "options": ["Osaka", "Kyoto", "Tokyo", "Hiroshima"], "answer": "Tokyo"},
    {"question": "Who wrote 'Harry Potter'?", "options": ["J.K. Rowling", "Stephen King", "George R.R. Martin", "J.R.R. Tolkien"], "answer": "J.K. Rowling"},
    {"question": "What is the largest mammal on Earth?", "options": ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], "answer": "Blue Whale"},
    {"question": "What is the capital of Germany?", "options": ["Munich", "Hamburg", "Berlin", "Cologne"], "answer": "Berlin"},
    {"question": "Which planet is known for its red color?", "options": ["Mars", "Jupiter", "Venus", "Uranus"], "answer": "Mars"},
    {"question": "Who invented the telephone?", "options": ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], "answer": "Alexander Graham Bell"},
    {"question": "What is the capital of Argentina?", "options": ["Cordoba", "Rosario", "Buenos Aires", "Mendoza"], "answer": "Buenos Aires"},
    {"question": "Which metal is liquid at room temperature?", "options": ["Iron", "Mercury", "Copper", "Gold"], "answer": "Mercury"},
    {"question": "What is the capital of Mexico?", "options": ["Guadalajara", "Monterrey", "Mexico City", "Tijuana"], "answer": "Mexico City"},
    {"question": "Who painted 'Starry Night'?", "options": ["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Henri Matisse"], "answer": "Vincent van Gogh"},
    {"question": "What is the smallest continent by land area?", "options": ["Europe", "Australia", "Antarctica", "South America"], "answer": "Australia"},
    {"question": "What is the capital of Greece?", "options": ["Thessaloniki", "Athens", "Patras", "Heraklion"], "answer": "Athens"},
    {"question": "Who was the first female Prime Minister of the United Kingdom?", "options": ["Theresa May", "Margaret Thatcher", "Golda Meir", "Indira Gandhi"], "answer": "Margaret Thatcher"},
    {"question": "What is the largest island in the world?", "options": ["Madagascar", "Greenland", "New Guinea", "Borneo"], "answer": "Greenland"},
    {"question": "Which gas do plants absorb from the atmosphere?", "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"], "answer": "Carbon Dioxide"},
    {"question": "What is the capital of Turkey?", "options": ["Izmir", "Ankara", "Istanbul", "Antalya"], "answer": "Ankara"},
    {"question": "Who discovered gravity?", "options": ["Galileo Galilei", "Isaac Newton", "Albert Einstein", "Nikola Tesla"], "answer": "Isaac Newton"},
    {"question": "What is the tallest waterfall in the world?", "options": ["Niagara", "Victoria", "Angel", "Iguazu"], "answer": "Angel"},
    {"question": "Which country is famous for the Eiffel Tower?", "options": ["Italy", "France", "Spain", "Germany"], "answer": "France"},
    {"question": "What is the capital of South Korea?", "options": ["Busan", "Incheon", "Seoul", "Daegu"], "answer": "Seoul"},
    {"question": "Who wrote 'The Great Gatsby'?", "options": ["Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck", "William Faulkner"], "answer": "F. Scott Fitzgerald"},
    {"question": "What is the fastest land animal?", "options": ["Cheetah", "Lion", "Horse", "Deer"], "answer": "Cheetah"},
    {"question": "What is the capital of Sweden?", "options": ["Gothenburg", "Stockholm", "Malmo", "Uppsala"], "answer": "Stockholm"},
    {"question": "Which element is the most abundant in the human body?", "options": ["Carbon", "Oxygen", "Hydrogen", "Nitrogen"], "answer": "Oxygen"},
    {"question": "Who was the first Emperor of Rome?", "options": ["Julius Caesar", "Augustus", "Nero", "Trajan"], "answer": "Augustus"},
    {"question": "What is the capital of Chile?", "options": ["Valparaiso", "Santiago", "Concepcion", "Antofagasta"], "answer": "Santiago"},
    {"question": "Which bird is a symbol of peace?", "options": ["Eagle", "Dove", "Owl", "Parrot"], "answer": "Dove"},
    {"question": "What is the capital of Portugal?", "options": ["Lisbon", "Porto", "Coimbra", "Braga"], "answer": "Lisbon"},
    {"question": "Who invented the light bulb?", "options": ["Thomas Edison", "Nikola Tesla", "Humphry Davy", "Joseph Swan"], "answer": "Thomas Edison"},
    {"question": "What is the deepest ocean?", "options": ["Atlantic", "Indian", "Arctic", "Pacific"], "answer": "Pacific"},
    {"question": "What is the capital of Norway?", "options": ["Bergen", "Oslo", "Trondheim", "Stavanger"], "answer": "Oslo"},
    {"question": "Which fruit is known for its vitamin C content?", "options": ["Banana", "Apple", "Orange", "Grape"], "answer": "Orange"},
    {"question": "Who was the first person to fly solo across the Atlantic?", "options": ["Amelia Earhart", "Charles Lindbergh", "Howard Hughes", "Wiley Post"], "answer": "Charles Lindbergh"},
    {"question": "What is the capital of Thailand?", "options": ["Chiang Mai", "Phuket", "Bangkok", "Pattaya"], "answer": "Bangkok"},
    {"question": "Which gas is used in balloons to make them float?", "options": ["Oxygen", "Helium", "Nitrogen", "Carbon Dioxide"], "answer": "Helium"},
    {"question": "What is the capital of Austria?", "options": ["Salzburg", "Vienna", "Graz", "Innsbruck"], "answer": "Vienna"},
    {"question": "Who wrote 'Pride and Prejudice'?", "options": ["Charlotte Bronte", "Jane Austen", "Emily Bronte", "Mary Shelley"], "answer": "Jane Austen"},
    {"question": "What is the largest volcano in the world?", "options": ["Mount Vesuvius", "Mount Etna", "Mauna Loa", "Mount Fuji"], "answer": "Mauna Loa"},
    {"question": "What is the capital of Denmark?", "options": ["Aarhus", "Odense", "Copenhagen", "Aalborg"], "answer": "Copenhagen"},
    {"question": "Which metal is the best conductor of electricity?", "options": ["Copper", "Iron", "Aluminum", "Gold"], "answer": "Copper"},
    {"question": "Who was the leader of Nazi Germany?", "options": ["Joseph Stalin", "Adolf Hitler", "Benito Mussolini", "Francisco Franco"], "answer": "Adolf Hitler"},
    {"question": "What is the capital of Finland?", "options": ["Turku", "Helsinki", "Tampere", "Oulu"], "answer": "Helsinki"},
    {"question": "Which insect is known for its honey production?", "options": ["Bee", "Ant", "Wasp", "Butterfly"], "answer": "Bee"},
    {"question": "What is the capital of Switzerland?", "options": ["Zurich", "Geneva", "Bern", "Basel"], "answer": "Bern"},
    {"question": "Who discovered the structure of DNA?", "options": ["Francis Crick", "James Watson", "Rosalind Franklin", "All of the above"], "answer": "All of the above"},
    {"question": "What is the capital of Ireland?", "options": ["Cork", "Galway", "Dublin", "Limerick"], "answer": "Dublin"},
    {"question": "Which animal is the largest living reptile?", "options": ["Crocodile", "Alligator", "Komodo Dragon", "Saltwater Crocodile"], "answer": "Saltwater Crocodile"},
    {"question": "What is the capital of New Zealand?", "options": ["Auckland", "Wellington", "Christchurch", "Hamilton"], "answer": "Wellington"},
    {"question": "Who painted 'The Last Supper'?", "options": ["Michelangelo", "Leonardo da Vinci", "Raphael", "Caravaggio"], "answer": "Leonardo da Vinci"},
    {"question": "What is the capital of Belgium?", "options": ["Bruges", "Antwerp", "Brussels", "Ghent"], "answer": "Brussels"},
    {"question": "Which planet has the most moons?", "options": ["Jupiter", "Saturn", "Uranus", "Neptune"], "answer": "Saturn"},
    {"question": "What is the capital of the Netherlands?", "options": ["Rotterdam", "Amsterdam", "Utrecht", "The Hague"], "answer": "Amsterdam"},
    {"question": "Who was the first woman to win an Olympic gold medal?", "options": ["Fanny Blankers-Koen", "Sonja Henie", "Charlotte Cooper", "Nadia Comaneci"], "answer": "Charlotte Cooper"},
    {"question": "What is the capital of Poland?", "options": ["Krakow", "Warsaw", "Gdansk", "Wroclaw"], "answer": "Warsaw"},
    {"question": "Which fish is known as the 'king of the sea'?", "options": ["Shark", "Tuna", "Salmon", "Cod"], "answer": "Shark"},
    {"question": "What is the capital of Hungary?", "options": ["Debrecen", "Szeged", "Budapest", "Pecs"], "answer": "Budapest"},
    {"question": "Who invented the World Wide Web?", "options": ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Larry Page"], "answer": "Tim Berners-Lee"},
    {"question": "What is the capital of Czech Republic?", "options": ["Brno", "Ostrava", "Prague", "Plzen"], "answer": "Prague"},
    {"question": "Which fruit is used to make wine?", "options": ["Apple", "Grape", "Pear", "Cherry"], "answer": "Grape"},
    {"question": "What is the capital of Ukraine?", "options": ["Lviv", "Odessa", "Kyiv", "Dnipro"], "answer": "Kyiv"},
    {"question": "Who was the first person to climb Mount Everest?", "options": ["Tenzing Norgay", "Edmund Hillary", "George Mallory", "Reinhold Messner"], "answer": "Edmund Hillary"},
    {"question": "What is the capital of Romania?", "options": ["Cluj-Napoca", "Timisoara", "Bucharest", "Iasi"], "answer": "Bucharest"},
    {"question": "Which animal is known for its black and white stripes?", "options": ["Zebra", "Tiger", "Leopard", "Giraffe"], "answer": "Zebra"},
    {"question": "What is the capital of Bulgaria?", "options": ["Plovdiv", "Varna", "Sofia", "Burgas"], "answer": "Sofia"},
    {"question": "Who wrote '1984'?", "options": ["George Orwell", "Aldous Huxley", "Ray Bradbury", "Isaac Asimov"], "answer": "George Orwell"},
    {"question": "What is the capital of Slovakia?", "options": ["Kosice", "Bratislava", "Presov", "Zilina"], "answer": "Bratislava"},
    {"question": "Which bird can mimic human speech?", "options": ["Parrot", "Crow", "Sparrow", "Pigeon"], "answer": "Parrot"},
    {"question": "What is the capital of Croatia?", "options": ["Split", "Zagreb", "Dubrovnik", "Rijeka"], "answer": "Zagreb"},
    {"question": "Who discovered electricity?", "options": ["Michael Faraday", "Benjamin Franklin", "Thomas Edison", "Nikola Tesla"], "answer": "Benjamin Franklin"},
    {"question": "What is the capital of Serbia?", "options": ["Novi Sad", "Belgrade", "Nis", "Kragujevac"], "answer": "Belgrade"},
    {"question": "Which vegetable is known for its red color?", "options": ["Carrot", "Tomato", "Potato", "Onion"], "answer": "Tomato"},
    {"question": "What is the capital of Lithuania?", "options": ["Kaunas", "Vilnius", "Klaipeda", "Siauliai"], "answer": "Vilnius"},
    {"question": "Who was the first Secretary-General of the United Nations?", "options": ["Dag Hammarskjöld", "Trygve Lie", "U Thant", "Kurt Waldheim"], "answer": "Trygve Lie"},
    {"question": "What is the capital of Latvia?", "options": ["Daugavpils", "Liepaja", "Riga", "Jelgava"], "answer": "Riga"},
    # ... (Continue adding up to ~50 English questions, then add ~50 Arabic questions, or expand to 500 total)
    {"question": "What is the capital of Macedonia?", "options": ["Bitola", "Skopje", "Prilep", "Kumanovo"], "answer": "Skopje"},

    # Arabic Trivia Questions
    {"question": "ما هي عاصمة مصر؟", "options": ["القاهرة", "باريس", "لندن", "برلين"], "answer": "القاهرة"},
    {"question": "من كتب رواية ألف ليلة وليلة؟", "options": ["نزار قباني", "جبران خليل جبران", "ألفونس دوديت", "محمد حسين هيكل"], "answer": "محمد حسين هيكل"},
    {"question": "ما هو أكبر قارة في العالم؟", "options": ["أفريقيا", "آسيا", "أوروبا", "أمريكا الشمالية"], "answer": "آسيا"},
    {"question": "ما هي عاصمة المغرب؟", "options": ["الدار البيضاء", "الرباط", "مراكش", "فاس"], "answer": "الرباط"},
    {"question": "من اكتشف الجزائر؟", "options": ["فرنسيس دراك", "خير الدين بربروس", "كريستوفر كولومبوس", "فرناندو ماجلان"], "answer": "خير الدين بربروس"},
    {"question": "ما هو أعلى جبل في الجزيرة العربية؟", "options": ["جبل الشفا", "جبل سيناء", "جبل الحجاز", "جبل الفلق"], "answer": "جبل الحجاز"},
    {"question": "ما هي عاصمة السعودية؟", "options": ["جدة", "الرياض", "مكة", "المدينة"], "answer": "الرياض"},
    {"question": "ما هو أطول نهر في العالم؟", "options": ["الأمازون", "النيل", "الغانج", "يانغتسي"], "answer": "النيل"},
{"question": "ما هي عاصمة البرازيل؟", "options": ["كانبيرا", "برلين", "ساو باولو", "ريو دي جانيرو"], "answer": "ريو دي جانيرو"},
    {"question": "من رسم لوحة الموناليزا؟", "options": ["فان جوخ", "بانيباس", "دا فينشي", "بيكاسو"], "answer": "دا فينشي"},
    {"question": "ما هو أكبر كوكب في المجموعة الشمسية؟", "options": ["الأرض", "المشتري", "زحل", "نبتون"], "answer": "المشتري"},
    {"question": "أي دولة تُعرف بأرض الشمس المشرقة؟", "options": ["الصين", "تايلاند", "اليابان", "فيتنام"], "answer": "اليابان"},
    {"question": "ما هو أعلى جبل في العالم؟", "options": ["K2", "كانجن چونجا", "إيفرست", "ماكالو"], "answer": "إيفرست"},
    {"question": "أي كوكب يُعرف بحلقاته؟", "options": ["المريخ", "المشتري", "زحل", "أورانوس"], "answer": "زحل"},
    {"question": "ما هي عاصمة فرنسا؟", "options": ["مدريد", "باريس", "روما", "برلين"], "answer": "باريس"},
    {"question": "من كان أول رئيس للولايات المتحدة؟", "options": ["توماس جيفرسون", "واشنطن", "آدامز", "لينكولن"], "answer": "واشنطن"},
    {"question": "ما هو أكبر صحراء في العالم؟", "options": ["الصحراء الكبرى", "جوبي", "أنتاركتيكا", "عربية"], "answer": "أنتاركتيكا"},
    {"question": "أي عنصر له الرمز الكيميائي O؟", "options": ["الذهب", "الأكسجين", "الحديد", "الفضة"], "answer": "الأكسجين"},
    {"question": "ما هي عاصمة أستراليا؟", "options": ["سيدني", "ملبورن", "كانبيرا", "بيرث"], "answer": "كانبيرا"},
    {"question": "من كتب روميو وجولييت؟", "options": ["تشارلز ديكنز", "ويليام شكسبير", "جين أوستن", "مارك توين"], "answer": "ويليام شكسبير"},
    {"question": "ما هي أصغر دولة في العالم مساحة؟", "options": ["موناكو", "ناورو", "مدينة الفاتيكان", "سان مارينو"], "answer": "مدينة الفاتيكان"},
    {"question": "أي حيوان يُعرف بملك الغابة؟", "options": ["الفيل", "الأسد", "النمر", "الدب"], "answer": "الأسد"},
    {"question": "ما المكون الرئيسي في الجواكامولي؟", "options": ["الطماطم", "الأفوكادو", "البصل", "الفلفل"], "answer": "الأفوكادو"},
    {"question": "أي كوكب هو الأقرب إلى الشمس؟", "options": ["الزهرة", "عطارد", "الأرض", "المريخ"], "answer": "عطارد"},
    {"question": "ما هي عاصمة كندا؟", "options": ["تورونتو", "فانكوفر", "أوتاوا", "مونتريال"], "answer": "أوتاوا"},
    {"question": "من اكتشف البنسلين؟", "options": ["ماري كوري", "ألكسندر فليمنغ", "لويس باستور", "إسحاق نيوتن"], "answer": "ألكسندر فليمنغ"},
    {"question": "ما هو أطول نهر في العالم؟", "options": ["الأمازون", "النيل", "يانغتسي", "المسيسيبي"], "answer": "النيل"},
    {"question": "أي رياضة تُلعب في ويمبلدون؟", "options": ["الكريكيت", "التنس", "كرة القدم", "الغولف"], "answer": "التنس"},
    {"question": "ما هي عاصمة مصر؟", "options": ["الإسكندرية", "القاهرة", "الأقصر", "الجيزة"], "answer": "القاهرة"},
    {"question": "من كان أول رجل يخطو على القمر؟", "options": ["باز ألدرين", "نيل أرمسترونغ", "يوري جاغارين", "جون غلين"], "answer": "نيل أرمسترونغ"},
    {"question": "ما هو أكبر محيط على الأرض؟", "options": ["الأطلسي", "الهندي", "القطبي", "المحيط الهادئ"], "answer": "المحيط الهادئ"},
    {"question": "أي غاز يشكل معظم الغلاف الجوي للأرض؟", "options": ["الأكسجين", "ثاني أكسيد الكربون", "النيتروجين", "الهيدروجين"], "answer": "النيتروجين"},
    {"question": "ما هي عاصمة الهند؟", "options": ["مومباي", "دلهي", "بنغالور", "كولكاتا"], "answer": "دلهي"},
    {"question": "من رسم سقف كنيسة سيستين؟", "options": ["ليوناردو دا فينشي", "مايكل أنجلو", "رافاييل", "تيشن"], "answer": "مايكل أنجلو"},
    {"question": "ما هو أصلب مادة طبيعية معروفة؟", "options": ["الذهب", "الماس", "الحديد", "الكوارتز"], "answer": "الماس"},
    {"question": "أي دولة استضافت أولمبياد 2016؟", "options": ["الصين", "البرازيل", "روسيا", "الولايات المتحدة"], "answer": "البرازيل"},
    {"question": "ما هي عاصمة جنوب إفريقيا؟", "options": ["يوهانسبورغ", "كيب تاون", "بريتوريا", "ديربان"], "answer": "بريتوريا"},
    {"question": "أي آلة موسيقية لها 88 مفتاحًا؟", "options": ["الغيتار", "البيانو", "الكمان", "الطبل"], "answer": "البيانو"},
    {"question": "ما هي عاصمة روسيا؟", "options": ["سانت بطرسبرغ", "موسكو", "نوفوسيبيرسك", "كازان"], "answer": "موسكو"},
    {"question": "من طور نظرية النسبية؟", "options": ["إسحاق نيوتن", "ألبرت أينشتاين", "ستيفن هوكينغ", "نيلز بور"], "answer": "ألبرت أينشتاين"},
    {"question": "ما هو أكبر طائر في العالم؟", "options": ["النسر", "النعامة", "البطريق", "الألباتروس"], "answer": "النعامة"},
    {"question": "ما هي عاصمة إيطاليا؟", "options": ["فينيسيا", "ميلانو", "روما", "فلورنسا"], "answer": "روما"},
    {"question": "أي غاز هو الأكثر وفرة في الكون؟", "options": ["الأكسجين", "الهيليوم", "الهيدروجين", "الكربون"], "answer": "الهيدروجين"},
    {"question": "من كانت أول امرأة تفوز بجائزة نوبل؟", "options": ["ماري كوري", "جين أدامز", "بيرل باك", "الأم تيريزا"], "answer": "ماري كوري"},
    {"question": "ما هي عاصمة إسبانيا؟", "options": ["برشلونة", "مدريد", "سévييا", "فالنسيا"], "answer": "مدريد"},
    {"question": "أي فاكهة تُعرف بقشرتها الشائكة؟", "options": ["المانجو", "الأناناس", "الموز", "التفاح"], "answer": "الأناناس"},
    {"question": "ما هي عاصمة اليابان؟", "options": ["أوساكا", "كيوتو", "طوكيو", "هيروشيما"], "answer": "طوكيو"},
    {"question": "من كتب هاري بوتر؟", "options": ["ج.ك. رولينغ", "ستيفن كينغ", "جورج ر.ر. مارتن", "ج.ر.ر. توكين"], "answer": "ج.ك. رولينغ"},
    {"question": "ما هو أكبر ثديي في العالم؟", "options": ["الفيل", "الحوت الأزرق", "الزرافة", "الجاموس"], "answer": "الحوت الأزرق"},
    {"question": "ما هي عاصمة ألمانيا؟", "options": ["ميونيخ", "هامبورغ", "برلين", "كولونيا"], "answer": "برلين"},
    {"question": "أي كوكب يُعرف بلونه الأحمر؟", "options": ["المريخ", "المشتري", "الزهرة", "أورانوس"], "answer": "المريخ"},
    {"question": "من اخترع الهاتف؟", "options": ["توماس إديسون", "ألكسندر غراهام بيل", "نيكولا تيسلا", "غوغليلمو ماركوني"], "answer": "ألكسندر غراهام بيل"},
    {"question": "ما هي عاصمة الأرجنتين؟", "options": ["كوردوبا", "روزاريو", "بوينس آيرس", "ميندوزا"], "answer": "بوينس آيرس"},
    {"question": "أي معدن سائل في درجة حرارة الغرفة؟", "options": ["الحديد", "الزئبق", "النحاس", "الذهب"], "answer": "الزئبق"},
    {"question": "ما هي عاصمة المكسيك؟", "options": ["غوادالاخارا", "مونتيري", "مدينة مكسيكو", "تيخوانا"], "answer": "مدينة مكسيكو"},
    {"question": "من رسم لوحة 'ليلة النجوم'؟", "options": ["كلود مونيه", "فينسنت فان غوخ", "بابلو بيكاسو", "هنري ماتيس"], "answer": "فينسنت فان غوخ"},
    {"question": "ما هو أصغر قارة مساحة؟", "options": ["أوروبا", "أستراليا", "أنتاركتيكا", "أمريكا الجنوبية"], "answer": "أستراليا"},
    {"question": "ما هي عاصمة اليونان؟", "options": ["ثيسالونيكي", "أثينا", "باتراس", "هيركليون"], "answer": "أثينا"},
    {"question": "من كانت أول رئيسة وزراء للمملكة المتحدة؟", "options": ["تيريزا ماي", "مارغريت ثاتشر", "غولدا مئير", "إنديرا غاندي"], "answer": "مارغريت ثاتشر"},
    {"question": "ما هو أكبر جزيرة في العالم؟", "options": ["مدغشقر", "غرينلاند", "غينيا الجديدة", "بورنيو"], "answer": "غرينلاند"},
    {"question": "أي غاز تستنشقه النباتات من الغلاف الجوي؟", "options": ["الأكسجين", "ثاني أكسيد الكربون", "النيتروجين", "الهيليوم"], "answer": "ثاني أكسيد الكربون"},
    {"question": "ما هي عاصمة تركيا؟", "options": ["إزمير", "أنقرة", "إسطنبول", "أنطاليا"], "answer": "أنقرة"},
    {"question": "من اكتشف الجاذبية؟", "options": ["جاليليو جاليلي", "إسحاق نيوتن", "ألبرت أينشتاين", "نيكولا تيسلا"], "answer": "إسحاق نيوتن"},
    {"question": "ما هو أعلى شلال في العالم؟", "options": ["نياجرا", "فيكتوريا", "أنجل", "إيغوازو"], "answer": "أنجل"},
    {"question": "أي بلد يشتهر ببرج إيفل؟", "options": ["إيطاليا", "فرنسا", "إسبانيا", "ألمانيا"], "answer": "فرنسا"},
    {"question": "ما هي عاصمة كوريا الجنوبية؟", "options": ["بوسان", "إنشيون", "سول", "دايغو"], "answer": "سول"},
    {"question": "من كتب 'الجاتسبي العظيم'؟", "options": ["إرنست همنغواي", "ف. سكوت فيتزجيرالد", "جون شتاينبيك", "ويليام فوكنر"], "answer": "ف. سكوت فيتزجيرالد"},
    {"question": "ما هو أسرع حيوان بري؟", "options": ["الفهد", "الأسد", "الحصان", "الغزال"], "answer": "الفهد"},
    {"question": "ما هي عاصمة السويد؟", "options": ["غوتنبرغ", "ستوكهولم", "مالمو", "أوبسالا"], "answer": "ستوكهولم"},
    {"question": "أي عنصر هو الأكثر وفرة في جسم الإنسان؟", "options": ["الكربون", "الأكسجين", "الهيدروجين", "النيتروجين"], "answer": "الأكسجين"},
    {"question": "من كان أول إمبراطور لروما؟", "options": ["يوليوس قيصر", "أوغسطس", "نيرون", "تراجان"], "answer": "أوغسطس"},
    {"question": "ما هي عاصمة تشيلي؟", "options": ["فالبارايسو", "سانتياغو", "كونسيبسيون", "أنتوفاغاستا"], "answer": "سانتياغو"},
    {"question": "أي طائر رمز السلام؟", "options": ["النسر", "الحمامة", "البومة", "الببغاء"], "answer": "الحمامة"},
    {"question": "ما هي عاصمة البرتغال؟", "options": ["لشبونة", "بورتو", "كويمبرا", "براغا"], "answer": "لشبونة"},
    {"question": "من اخترع المصباح الكهربائي؟", "options": ["توماس إديسون", "نيكولا تيسلا", "هامفري دافي", "جوزيف سوان"], "answer": "توماس إديسون"},
    {"question": "ما هو أعمق محيط؟", "options": ["الأطلسي", "الهندي", "القطبي", "المحيط الهادئ"], "answer": "المحيط الهادئ"},
    {"question": "ما هي عاصمة النرويج؟", "options": ["برغن", "أوسلو", "تروندهايم", "ستافانغر"], "answer": "أوسلو"},
    {"question": "أي فاكهة تُعرف بمحتواها من فيتامين C؟", "options": ["الموز", "التفاح", "البرتقال", "العنب"], "answer": "البرتقال"},
    {"question": "من كان أول شخص يطير عبر المحيط الأطلسي بمفرده؟", "options": ["أميليا إيرهارت", "تشارلز ليندبيرغ", "هوارد هيوز", "وايلي بوست"], "answer": "تشارلز ليندبيرغ"},
    {"question": "ما هي عاصمة تايلاند؟", "options": ["تشيانغ ماي", "فوكيت", "بانكوك", "باتايا"], "answer": "بانكوك"},
    {"question": "أي غاز يُستخدم في البالونات لجعلها تطفو؟", "options": ["الأكسجين", "الهيليوم", "النيتروجين", "ثاني أكسيد الكربون"], "answer": "الهيليوم"},
    {"question": "ما هي عاصمة النمسا؟", "options": ["سالزبورغ", "فيينا", "غراز", "إنسبروك"], "answer": "فيينا"},
    {"question": "من كتب 'فخر وتحامل'؟", "options": ["شارلوت برونتي", "جين أوستن", "إيميلي برونتي", "ماري شيلي"], "answer": "جين أوستن"},
    {"question": "ما هو أكبر بركان في العالم؟", "options": ["جبل فزوف", "جبل إتنا", "ماونا لوا", "جبل فوجي"], "answer": "ماونا لوا"},
    {"question": "ما هي عاصمة الدنمارك؟", "options": ["آرهوس", "أودنسه", "كوبنهاغن", "آلبورغ"], "answer": "كوبنهاغن"},
    {"question": "أي معدن هو أفضل موصل للكهرباء؟", "options": ["النحاس", "الحديد", "الألمنيوم", "الذهب"], "answer": "النحاس"},
    {"question": "من كان زعيم ألمانيا النازية؟", "options": ["جوزيف ستالين", "أدولف هتلر", "بينيتو موسوليني", "فرانسيسكو فرانكو"], "answer": "أدولف هتلر"},
    {"question": "ما هي عاصمة فنلندا؟", "options": ["توركو", "هلسنكي", "تامبيري", "أولو"], "answer": "هلسنكي"},
    {"question": "أي حشرة تُعرف بإنتاج العسل؟", "options": ["النحلة", "النمل", "الدبور", "الفراشة"], "answer": "النحلة"},
    {"question": "ما هي عاصمة سويسرا؟", "options": ["زيورخ", "جنيف", "برن", "بازل"], "answer": "برن"},
    {"question": "من اكتشف هيكل الـDNA؟", "options": ["فرانسيس كريك", "جيمس واطسون", "روزاليند فرانكلين", "الجميع أعلاه"], "answer": "الجميع أعلاه"},
    {"question": "ما هي عاصمة أيرلندا؟", "options": ["كورك", "غالواي", "دبلن", "ليميريك"], "answer": "دبلن"},
    {"question": "أي حيوان هو أكبر زاحف حي؟", "options": ["التمساح", "الأسد", "تنين كومودو", "تمساح المياه المالحة"], "answer": "تمساح المياه المالحة"},
    {"question": "ما هي عاصمة نيوزيلندا؟", "options": ["أوكلاند", "ويلينغتون", "كرايستشرش", "هاميلتون"], "answer": "ويلينغتون"},
    {"question": "من رسم 'العشاء الأخير'؟", "options": ["مايكل أنجلو", "ليوناردو دا فينشي", "رافاييل", "كارافاجيو"], "answer": "ليوناردو دا فينشي"},
    {"question": "ما هي عاصمة بلجيكا؟", "options": ["بروج", "أنتWERP", "بروكسل", "غنت"], "answer": "بروكسل"},
    {"question": "أي كوكب لديه أكثر الأقمار؟", "options": ["المشتري", "زحل", "أورانوس", "نبتون"], "answer": "زحل"},
    {"question": "ما هي عاصمة هولندا؟", "options": ["روتردام", "أمستردام", "أوترخت", "ذا Hague"], "answer": "أمستردام"},
    {"question": "من كانت أول امرأة تفوز بميدالية ذهبية أولمبية؟", "options": ["فاني بلانكرز-كوين", "سونيا هيني", "شارلوت كوبر", "نادية كومانيتش"], "answer": "شارلوت كوبر"},
    {"question": "ما هي عاصمة بولندا؟", "options": ["كراكوف", "وارسو", "غدانسك", "وروكلاو"], "answer": "وارسو"},
    {"question": "أي سمكة تُعرف بملك البحر؟", "options": ["القرش", "التونة", "السلمون", "الكود"], "answer": "القرش"},
    {"question": "ما هي عاصمة المجر؟", "options": ["ديبرتسن", "سيزجيد", "بودابست", "بيتش"], "answer": "بودابست"},
    {"question": "من اخترع الوِب العالمي؟", "options": ["بيل غيتس", "تيم برنرز-لي", "ستيف جوبز", "لاري بيج"], "answer": "تيم برنرز-لي"},
    {"question": "ما هي عاصمة التشيك؟", "options": ["برنو", "أوسترافا", "براغ", "بلزن"], "answer": "براغ"},
    {"question": "أي فاكهة تُستخدم لصنع النبيذ؟", "options": ["التفاح", "العنب", "الإجاص", "الكرز"], "answer": "العنب"},
    {"question": "ما هي عاصمة أوكرانيا؟", "options": ["ليفيف", "أوديسا", "كييف", "دنيبرو"], "answer": "كييف"},
    {"question": "من كان أول شخص يتسلق جبل إيفرست؟", "options": ["تينزين نورغاي", "إدموند هيلاري", "جورج مالوري", "راينهولد ميسنر"], "answer": "إدموند هيلاري"},
    {"question": "ما هي عاصمة رومانيا؟", "options": ["كلوج-نابوكا", "تيميشوارا", "بوخارست", "ياسي"], "answer": "بوخارست"},
    {"question": "أي حيوان يُعرف بخطوطه البيضاء والسوداء؟", "options": ["الزبرا", "النمر", "الفهد", "الزرافة"], "answer": "الزبرا"},
    {"question": "ما هي عاصمة بلغاريا؟", "options": ["بلوفديف", "وارنا", "صوفيا", "بورغاس"], "answer": "صوفيا"},
    {"question": "من كتب '1984'؟", "options": ["جورج أورويل", "ألدوس هكسلي", "راي برادبري", "إسحاق أسيروف"], "answer": "جورج أورويل"},
    {"question": "ما هي عاصمة سلوفاكيا؟", "options": ["كوشيتسه", "براتيسلافا", "بريشوف", "زيلينا"], "answer": "براتيسلافا"},
    {"question": "أي طائر يمكنه تقليد الكلام البشري؟", "options": ["الببغاء", "الغراب", "العصفور", "الحمامة"], "answer": "الببغاء"},
    {"question": "ما هي عاصمة كرواتيا؟", "options": ["سبليت", "زغرب", "دوبروفنيك", "رييكا"], "answer": "زغرب"},
    {"question": "من اكتشف الكهرباء؟", "options": ["مايكل فاراداي", "بنجامين فرانكلين", "توماس إديسون", "نيكولا تيسلا"], "answer": "بنجامين فرانكلين"},
    {"question": "ما هي عاصمة صربيا؟", "options": ["نووي ساد", "بلغراد", "نيش", "كراغويفاتس"], "answer": "بلغراد"},
    {"question": "أي خضروات تُعرف بلونها الأحمر؟", "options": ["الجزر", "الطماطم", "البطاطس", "البصل"], "answer": "الطماطم"},
    {"question": "ما هي عاصمة ليتوانيا؟", "options": ["كاوناس", "فيلنيوس", "كلايبيدا", "شياو لياي"], "answer": "فيلنيوس"},
    {"question": "من كان أول أمين عام للأمم المتحدة؟", "options": ["داغ هامرشولد", "تريغفي لي", "يو ثانت", "كورت فالدهيم"], "answer": "تريغفي لي"},
    {"question": "ما هي عاصمة لاتفيا؟", "options": ["داوغافبيلز", "لييبايا", "ريغا", "جيلغافا"], "answer": "ريغا"},
    # ... (Continue adding up to ~50 Arabic questions, or expand to 500 total)
    {"question": "ما هي عاصمة تونس؟", "options": ["القيروان", "تونس", "سوسة", "منوبة"], "answer": "تونس"}
    # Add 450 more English and Arabic trivia questions to reach 500 total
]

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/thought/<lang>')
def get_thought(lang):
    if lang == 'en':
        thought = random.choice(thoughts_quotes_en)
    elif lang == 'ar':
        thought = random.choice(thoughts_quotes_ar)
    else:
        thought = "Language not supported."
    return jsonify({"thought": thought})

@app.route('/trivia', methods=["POST"])
def trivia():
    data = request.json
    question_id = int(data.get('question_id', -1))
    selected_option = data.get('selected_option')

    # Log the received data for debugging
    print(f"Received data: question_id={question_id}, selected_option={selected_option}")

    if selected_option is None:
        return jsonify({"error": "No option selected."}), 400

    # Ensure the question_id is within the valid range
    if 0 <= question_id < len(trivia_questions):
        question = trivia_questions[question_id]
        correct_answer = question['answer']

        # Log the retrieved question and correct answer for debugging
        print(f"Retrieved question: {question}")
        print(f"Correct answer: {correct_answer}")

        is_correct = (selected_option == correct_answer)
    else:
        is_correct = False
        correct_answer = "Invalid question ID"

    return jsonify({"is_correct": is_correct, "correct_answer": correct_answer})

@app.route('/trivia_question/<lang>')
def trivia_question(lang):
    if lang == 'en':
        question_pool = [q for q in trivia_questions if q['question'].startswith('What') or q['question'].startswith('Who')]
    elif lang == 'ar':
        question_pool = [q for q in trivia_questions if q['question'].startswith('ما') or q['question'].startswith('من')]
    else:
        return jsonify({"error": "Language not supported."})

    if not question_pool:
        return jsonify({"error": "No questions available for this language."})

    question_id = random.randint(0, len(question_pool) - 1)
    question = question_pool[question_id]
    return jsonify({"question_id": trivia_questions.index(question), "question": question["question"], "options": question["options"]})

if __name__ == '__main__':
    app.run(debug=True)
